// ─────────────────────────────────────────────────────────────────────────────
// GrumpyDuck — Intelligence Detection Rules & Patterns
// ─────────────────────────────────────────────────────────────────────────────

import { IntelligenceCategory } from '../types/intelligence';

/** Common dataset filename keywords (case-insensitive substring or token match). */
export const DATASET_FILENAME_PATTERNS = [
  'training-set',
  'testing-set',
  'dataset',
  'features',
  'groundtruth',
  'ground-truth',
  'validation-set',
  'train_set',
  'test_set',
  'val_set',
  'train-',
  'test-',
  'val-',
  '_train',
  '_test',
  '_val',
  'labels',
  'corpus',
  'embeddings',
  'unsw-nb15',
  'mnist',
  'cifar',
  'imagenet',
  'benchmark',
];

/** Keywords indicating application installers or setup binaries. */
export const INSTALLER_FILENAME_PATTERNS = [
  'installer',
  'install',
  'setup',
  'update',
  'updater',
  'standalone',
];

/** Keywords indicating backup or archived working state. */
export const BACKUP_FILENAME_PATTERNS = [
  'backup',
  'backup-final',
  'archive',
  'bak',
  'old',
  'copy',
  'snapshot',
  'dump',
];

/** Directory names typically representing development dependencies, build outputs, or caches. */
export const DEV_DIRECTORY_NAMES = new Set([
  'node_modules',
  'dist',
  'build',
  'bin',
  'obj',
  'target',
  '__pycache__',
  '.venv',
  'venv',
  'env',
  '.next',
  '.nuxt',
  '.cache',
  'coverage',
  '.gradle',
  '.idea',
  '.vs',
  '.git',
  '.turbo',
  'vendor',
  'runtimes',
  'deriveddata',
  'pods',
  '.cargo',
  'out',
]);

/** File extensions of generated artifacts, compiled outputs, or debug files. */
export const DEV_ARTIFACT_EXTENSIONS = new Set([
  'pyc',
  'pyo',
  'class',
  'o',
  'obj',
  'dll',
  'pdb',
  'dylib',
  'so',
  'a',
  'map',
  'lock',
  'nupkg',
  'manifest',
  'd.ts',
  'tsbuildinfo',
]);

/** File extensions for application installers and disk images. */
export const INSTALLER_EXTENSIONS = new Set([
  'dmg',
  'pkg',
  'exe',
  'msi',
  'iso',
  'deb',
  'rpm',
  'appimage',
  'snap',
]);

/** File extensions for temporary or scratch files. */
export const TEMPORARY_EXTENSIONS = new Set([
  'tmp',
  'temp',
  'swp',
  'swo',
  'bak',
  'log',
  'ds_store',
]);

/** Dataset-specific or data tabular extensions. */
export const DATA_EXTENSIONS = new Set([
  'csv',
  'tsv',
  'parquet',
  'feather',
  'arrow',
  'hdf5',
  'h5',
  'pkl',
  'pickle',
  'npy',
  'npz',
  'mat',
  'arff',
]);

/** Maps standard file categories/extensions to base IntelligenceCategory. */
export const EXTENSION_TO_CATEGORY: Record<string, IntelligenceCategory> = {
  // Documents
  pdf: 'DOCUMENT',
  doc: 'DOCUMENT',
  docx: 'DOCUMENT',
  xls: 'DOCUMENT',
  xlsx: 'DOCUMENT',
  ppt: 'DOCUMENT',
  pptx: 'DOCUMENT',
  odt: 'DOCUMENT',
  ods: 'DOCUMENT',
  odp: 'DOCUMENT',
  txt: 'DOCUMENT',
  rtf: 'DOCUMENT',
  md: 'DOCUMENT',
  markdown: 'DOCUMENT',
  epub: 'DOCUMENT',
  mobi: 'DOCUMENT',
  pages: 'DOCUMENT',
  numbers: 'DOCUMENT',
  keynote: 'DOCUMENT',

  // Data / Datasets base
  csv: 'DOCUMENT', // Default to DOCUMENT unless dataset patterns match
  tsv: 'DOCUMENT',
  parquet: 'DATASET',
  feather: 'DATASET',
  arrow: 'DATASET',
  hdf5: 'DATASET',
  h5: 'DATASET',
  npy: 'DATASET',
  npz: 'DATASET',
  arff: 'DATASET',

  // Images
  jpg: 'IMAGE',
  jpeg: 'IMAGE',
  png: 'IMAGE',
  gif: 'IMAGE',
  bmp: 'IMAGE',
  svg: 'IMAGE',
  webp: 'IMAGE',
  tiff: 'IMAGE',
  tif: 'IMAGE',
  heic: 'IMAGE',
  heif: 'IMAGE',
  ico: 'IMAGE',
  raw: 'IMAGE',
  cr2: 'IMAGE',
  nef: 'IMAGE',
  arw: 'IMAGE',
  dng: 'IMAGE',
  psd: 'IMAGE',
  xcf: 'IMAGE',

  // Videos
  mp4: 'VIDEO',
  mkv: 'VIDEO',
  avi: 'VIDEO',
  mov: 'VIDEO',
  wmv: 'VIDEO',
  flv: 'VIDEO',
  webm: 'VIDEO',
  m4v: 'VIDEO',
  mpg: 'VIDEO',
  mpeg: 'VIDEO',
  '3gp': 'VIDEO',
  mts: 'VIDEO',
  m2ts: 'VIDEO',
  vob: 'VIDEO',
  ogv: 'VIDEO',

  // Audio
  mp3: 'AUDIO',
  wav: 'AUDIO',
  flac: 'AUDIO',
  aac: 'AUDIO',
  ogg: 'AUDIO',
  wma: 'AUDIO',
  m4a: 'AUDIO',
  aiff: 'AUDIO',
  aif: 'AUDIO',
  opus: 'AUDIO',
  mid: 'AUDIO',
  midi: 'AUDIO',

  // Archives
  zip: 'ARCHIVE',
  tar: 'ARCHIVE',
  gz: 'ARCHIVE',
  bz2: 'ARCHIVE',
  xz: 'ARCHIVE',
  '7z': 'ARCHIVE',
  rar: 'ARCHIVE',
  tgz: 'ARCHIVE',
  tbz2: 'ARCHIVE',
  zst: 'ARCHIVE',
  lz4: 'ARCHIVE',
  lzma: 'ARCHIVE',
  cab: 'ARCHIVE',

  // Installers
  dmg: 'INSTALLER',
  pkg: 'INSTALLER',
  exe: 'INSTALLER',
  msi: 'INSTALLER',
  deb: 'INSTALLER',
  rpm: 'INSTALLER',
  appimage: 'INSTALLER',
  snap: 'INSTALLER',
  iso: 'INSTALLER',

  // Code
  js: 'CODE',
  mjs: 'CODE',
  cjs: 'CODE',
  ts: 'CODE',
  tsx: 'CODE',
  jsx: 'CODE',
  py: 'CODE',
  rb: 'CODE',
  rs: 'CODE',
  go: 'CODE',
  java: 'CODE',
  kt: 'CODE',
  swift: 'CODE',
  c: 'CODE',
  cpp: 'CODE',
  cc: 'CODE',
  h: 'CODE',
  hpp: 'CODE',
  cs: 'CODE',
  php: 'CODE',
  sh: 'CODE',
  bash: 'CODE',
  zsh: 'CODE',
  fish: 'CODE',
  ps1: 'CODE',
  html: 'CODE',
  css: 'CODE',
  scss: 'CODE',
  sass: 'CODE',
  json: 'CODE',
  yaml: 'CODE',
  yml: 'CODE',
  toml: 'CODE',
  xml: 'CODE',
  sql: 'CODE',
  graphql: 'CODE',
  gql: 'CODE',
  vue: 'CODE',
  svelte: 'CODE',
  dart: 'CODE',
  lua: 'CODE',
  r: 'CODE',
  matlab: 'CODE',
  pl: 'CODE',
  ex: 'CODE',
  exs: 'CODE',
  erl: 'CODE',
  hs: 'CODE',
  elm: 'CODE',
  clj: 'CODE',
  scala: 'CODE',
  nim: 'CODE',
  zig: 'CODE',

  // App Bundles
  app: 'APPLICATION',
  bundle: 'APPLICATION',
  framework: 'APPLICATION',
  plugin: 'APPLICATION',
  kext: 'APPLICATION',
  xpc: 'APPLICATION',

  // Temporary
  tmp: 'TEMPORARY_FILE',
  temp: 'TEMPORARY_FILE',
  swp: 'TEMPORARY_FILE',
  swo: 'TEMPORARY_FILE',
  bak: 'TEMPORARY_FILE',

  // Dev Artifacts
  pyc: 'DEVELOPMENT_ARTIFACT',
  pyo: 'DEVELOPMENT_ARTIFACT',
  class: 'DEVELOPMENT_ARTIFACT',
  o: 'DEVELOPMENT_ARTIFACT',
  obj: 'DEVELOPMENT_ARTIFACT',
  dll: 'DEVELOPMENT_ARTIFACT',
  pdb: 'DEVELOPMENT_ARTIFACT',
  dylib: 'DEVELOPMENT_ARTIFACT',
  so: 'DEVELOPMENT_ARTIFACT',
  a: 'DEVELOPMENT_ARTIFACT',
  map: 'DEVELOPMENT_ARTIFACT',
};
